package it.mmzitarosa.api2pojo.utils;

import java.util.Date;

public class Utility {

    public static String capitalize(String string) {
        String s1 = string.substring(0, 1).toUpperCase();
        return s1 + string.substring(1); //Capitalize
    }

    public static String joinStrings(char joinChar, String... strings) {
        StringBuilder stringBuilder = new StringBuilder();
        for (int i = 0; i < strings.length - 1; i++) {
            stringBuilder.append(strings[i]).append(joinChar);
        }
        stringBuilder.append(strings[strings.length - 1]);
        return stringBuilder.toString();
    }

    public static String generateHeaderComment() {
        Date date = new Date();
        return "/**\n" +
                "* This file was generated by Api2Pojo\n" +
                "* See <a href=\"https://github.com/mmzitarosa/Api2Pojo\">https://github.com/mmzitarosa/Api2Pojo</a> \n" +
                "* Any modifications to this file will be lost upon recompilation of the source schema. \n" +
                "* Generated on: " + date.toString() + " \n" +
                "*/";
    }

}
